In [1]:
# To build a XGBoost model for prediction of car quality given other attributes about the car

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
## Read Data
dataset = pd.read_csv('car.data',header= None,names=['buying','maint','doors','persons','lug_boot','safety','class'])

In [3]:
dataset.shape

(1728, 7)

In [4]:
dataset.head()

buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [5]:
## profiling data
dataset['buying'].value_counts()

vhigh    432
high     432
med      432
low      432
Name: buying, dtype: int64

In [6]:
## profiling data
dataset['maint'].value_counts()

vhigh    432
high     432
med      432
low      432
Name: maint, dtype: int64

In [7]:
## profiling data
dataset['doors'].value_counts()

3        432
2        432
4        432
5more    432
Name: doors, dtype: int64

In [8]:
## profiling data
dataset['persons'].value_counts()

more    576
2       576
4       576
Name: persons, dtype: int64

In [7]:
X = pd.get_dummies(dataset.iloc[:,:-1],drop_first=True)

In [8]:
X.head()
y=dataset['class']

In [9]:
X.head()

buying_low  buying_med  buying_vhigh  maint_low  maint_med  maint_vhigh  \
0           0           0             1          0          0            1   
1           0           0             1          0          0            1   
2           0           0             1          0          0            1   
3           0           0             1          0          0            1   
4           0           0             1          0          0            1   

   doors_3  doors_4  doors_5more  persons_4  persons_more  lug_boot_med  \
0        0        0            0          0             0             0   
1        0        0            0          0             0             0   
2        0        0            0          0             0             0   
3        0        0            0          0             0             1   
4        0        0            0          0             0             1   

   lug_boot_small  safety_low  safety_med  
0               1           1           0  
1               1           0           1  
2               1           0           0  
3               0           1           0  
4               0           0           1

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=101, test_size=0.10)

In [11]:
# calculate cross-validated AUC
from sklearn import svm
from xgboost import XGBClassifier
clf = XGBClassifier()
clf

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bynode=1, colsample_bytree=1, gamma=0, learning_rate=0.1,
       max_delta_step=0, max_depth=3, min_child_weight=1, missing=None,
       n_estimators=100, n_jobs=1, nthread=None,
       objective='binary:logistic', random_state=0, reg_alpha=0,
       reg_lambda=1, scale_pos_weight=1, seed=None, silent=None,
       subsample=1, verbosity=1)

In [12]:
# use the model to make predictions with the test data
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
# Import metrics
from sklearn import metrics
# generate evaluation metrics-
print(metrics.accuracy_score(y_test, y_pred))

0.9190751445086706


In [13]:
# Print out the confusion matrix
print(metrics.confusion_matrix(y_test, y_pred))

[[ 28   1   1   0]
 [  0   4   0   1]
 [  9   2 121   0]
 [  0   0   0   6]]


In [14]:
# Print out the classification report, and check the f1 score
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         acc       0.76      0.93      0.84        30
        good       0.57      0.80      0.67         5
       unacc       0.99      0.92      0.95       132
       vgood       0.86      1.00      0.92         6

   micro avg       0.92      0.92      0.92       173
   macro avg       0.79      0.91      0.84       173
weighted avg       0.93      0.92      0.92       173



In [15]:
y_pred=pd.DataFrame(data=y_pred,columns=['Predicted'])
id = pd.DataFrame(data=X_test.index.values,columns=['ID'])
output=pd.concat([id,y_pred],axis=1)
output.to_csv('XGBoost_Casestudy_3_Session23.csv',index=False)